-- CREATE TABLE companies (
--   id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
--   name VARCHAR(255),
--   establishment_date DATE,
--   founder VARCHAR(255),
--   created_at TIMESTAMP NOT NULL DEFAULT
--   CURRENT_TIMESTAMP
-- ) DEFAULT CHARACTER SET=utf8mb4;

-- CREATE TABLE log (
--   id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
--   title VARCHAR(255),
--   writer VARCHAR(255),
--   score INT ,
--   thou VARCHAR(1000),
--   created_at TIMESTAMP NOT NULL DEFAULT
--   CURRENT_TIMESTAMP
-- ) DEFAULT CHARACTER SET=utf8mb4;
   DROP TABLE IF EXISTS reviews;
CREATE TABLE reviews (
    id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255),
    author VARCHAR(255),
    content VARCHAR(1000)
)DEFAULT CHARACTER SET=utf8mb4;
DROP TABLE IF EXISTS diary;
CREATE TABLE diary (
    id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(100),
    created_at TIMESTAMP NOT NULL DEFAULT
    CURRENT_TIMESTAMP,
    content VARCHAR(1000),
    score INTEGER
)DEFAULT CHARACTER SET=utf8mb4;
